name: dev-vcs/gitleaks golang vendor dist

on:
  workflow_dispatch:
    inputs:
      version:
        description: "gitleaks version tag (e.g. 8.18.0)"
        required: true

permissions:
  contents: write

jobs:
  golang-dist:
    uses: ./.github/workflows/go-modules.yml
    with:
      project: gitleaks
      repository: zricethezav/gitleaks
      version: ${{ inputs.version }}
