name: net-analyzer/brutus golang vendor dist

on:
  workflow_dispatch:
    inputs:
      version:
        description: "brutus version tag (e.g. 1.6.1)"
        required: true

permissions:
  contents: write

jobs:
  golang-dist:
    uses: ./.github/workflows/go-modules.yml
    with:
      project: brutus
      repository: praetorian-inc/brutus
      version: ${{ inputs.version }}
